Wvw
Archomeda/Gw2Sharp pull request #80
Opened 2020-12-08 18:47 UTC by werdes

2020-12-08 22:13 UTC, Archomeda commented
/test

2020-12-08 22:42 UTC, Archomeda requested changes
Thanks for your contribution!

There's something I'd like to address before merging:
Can you recheck all xmldoc comments and make sure that they have correct casing that are in line with the other comments? E.g. starting with a uppercase letter, WvW properly cased, id(s) fully lowercase, ending with a dot, etc.

Additionally, I'll have to think about the naming of WvwMatchWorldIdContainer and WvwMatchWorldValueContainer a bit more. I'm sure I've used similar models that are referenced from multiple places (instead of just one reference), but I can't remember it on the top of my head where exactly.

2020-12-08 22:42 UTC, Archomeda commented on Gw2Sharp/WebApi/V2/Clients/Wvw/WvwClient.cs
> +        /// Creates a new <see cref="WvwClient"/> that is used for the API v2 commerce endpoint.
I'm sure that this is not the commerce endpoint 😄

2020-12-08 23:28 UTC, werdes commented
> Additionally, I'll have to think about the naming of WvwMatchWorldIdContainer and WvwMatchWorldValueContainer a bit more. I'm sure I've used similar models that are referenced from multiple places (instead of just one reference), but I can't remember it on the top of my head where exactly.

Yeah i thought about that too. Another way to display those would be a `Dictionary<WvwOwner,  int>`, but i think that would not fit the rest of your inplementation, would it?

And damn, i missed that one commerce comment, that‘s what i get for copy/paste

2020-12-22 21:01 UTC, Archomeda commented
/test

2020-12-22 21:28 UTC, Archomeda commented
/test

2020-12-22 21:35 UTC, Archomeda approved these changes
I've gone over the code again, and made some additional changes. I also went ahead and added the subendpoints under /v2/wvw/matches into this PR.

Given that the guild and team stats are still broken on the API, I call this WvW PR feature complete. After merging, I'll make sure to update all documentation related files in another PR.

Thanks again!

2020-12-22 21:45 UTC, merged